import { Candidate } from "./randomUser";
import { Gender } from "./sillyNames";

/**
 * A fully-fleshed persona for a role, generated by the runtime's `candidates.generate`
 * command. Mirror of the sidecar's `PersonaCandidate` (kept in sync by hand — the
 * Node/browser split means no shared package). Deliberately name/gender-neutral so it
 * can be paired with any silly name + photo.
 */
export interface PersonaCandidate {
  personalityLabel: string;
  summary: string;
  mission: string;
  preamble: string;
  responsibilities: string[];
  additionalDetails: string;
  personality: string;
  communicationStyle: string;
  expertise: string[];
}

/** A generated persona paired with a display identity (silly name + gender-matched photo). */
export type FullCandidate = PersonaCandidate & {
  name: string;
  gender: Gender;
  photoUrl: string;
};

/**
 * Pairs generated personas with display identities by index. The two lists are
 * produced independently (one LLM call, one randomuser.me/silly-name fetch), so the
 * result length is the shorter of the two.
 */
export function zipCandidates(personas: PersonaCandidate[], bases: Candidate[]): FullCandidate[] {
  const n = Math.min(personas.length, bases.length);
  const out: FullCandidate[] = [];
  for (let i = 0; i < n; i++) {
    out.push({ ...personas[i], name: bases[i].name, gender: bases[i].gender, photoUrl: bases[i].photoUrl });
  }
  return out;
}
