export type Gender = "male" | "female";

export interface SillyName {
  name: string;
  gender: Gender;
}

export const SILLY_NAMES: SillyName[] = [
  { name: "Ben Dover", gender: "male" },
  { name: "Mike Oxlong", gender: "male" },
  { name: "Seymour Cox", gender: "male" },
  { name: "Amanda Hugginkiss", gender: "female" },
  { name: "Hugh Jass", gender: "male" },
  { name: "Al Coholic", gender: "male" },
  { name: "Jenny Talia", gender: "female" },
  { name: "Barry McKockiner", gender: "male" },
  { name: "Ivana Tinkle", gender: "female" },
  { name: "Oliver Klozoff", gender: "male" },
  { name: "Anita Bath", gender: "female" },
  { name: "Warren Peace", gender: "male" },
  { name: "Justin Case", gender: "male" },
  { name: "Phil McCracken", gender: "male" },
  { name: "Chris P. Bacon", gender: "male" },
  { name: "Dixie Normous", gender: "female" },
  { name: "Harry Balzac", gender: "male" },
  { name: "Wayne Kerr", gender: "male" },
  { name: "Pat Myback", gender: "male" },
  { name: "Stan Dupp", gender: "male" },
  { name: "Rick O'Shea", gender: "male" },
  { name: "Doug Graves", gender: "male" },
  { name: "Terry Aki", gender: "male" },
  { name: "Manny Facture", gender: "male" },
  { name: "Sandy Beach", gender: "female" },
  { name: "Rusty Shackleford", gender: "male" },
  { name: "Moe Lester", gender: "male" },
  { name: "Bill Ding", gender: "male" },
  { name: "Woody Fallwell", gender: "male" },
  { name: "Al B. Sure", gender: "male" },
  { name: "Bob Katz", gender: "male" },
  { name: "Gladys Friday", gender: "female" },
  { name: "Sue Permann", gender: "female" },
  { name: "Duncan Idaho", gender: "male" },
  { name: "Bud Wiser", gender: "male" },
  { name: "Heywood Jablome", gender: "male" },
  { name: "I.P. Freely", gender: "male" },
  { name: "Ollie Tabooger", gender: "male" },
  { name: "Mike Rotch", gender: "male" },
  { name: "Hugh Janus", gender: "male" },
  { name: "Seymour Butts", gender: "male" },
  { name: "Anita Mann", gender: "female" },
  { name: "Barb Dwyer", gender: "female" },
  { name: "Ben Thair", gender: "male" },
  { name: "Bea O'Problem", gender: "female" },
  { name: "Barry Cade", gender: "male" },
  { name: "Bill Board", gender: "male" },
  { name: "Cara Van", gender: "female" },
  { name: "Carrie Oakey", gender: "female" },
  { name: "Chip Munk", gender: "male" },
  { name: "Chuck Roast", gender: "male" },
  { name: "Claire Voyant", gender: "female" },
  { name: "Cliff Hanger", gender: "male" },
  { name: "Crystal Ball", gender: "female" },
  { name: "Dan Druff", gender: "male" },
  { name: "Dinah Mite", gender: "female" },
  { name: "Don Keigh", gender: "male" },
  { name: "Doug Hole", gender: "male" },
  { name: "Earl Lee Riser", gender: "male" },
  { name: "Eileen Dover", gender: "female" },
  { name: "Ella Vader", gender: "female" },
  { name: "Ferris Wheeler", gender: "male" },
  { name: "Frank N. Stein", gender: "male" },
  { name: "Gail Force", gender: "female" },
  { name: "Gene Poole", gender: "male" },
  { name: "Ginger Snapp", gender: "female" },
  { name: "Hal Appeno", gender: "male" },
  { name: "Harry Legg", gender: "male" },
  { name: "Hazel Nutt", gender: "female" },
  { name: "Holly Wood", gender: "female" },
  { name: "Hugh Mungus", gender: "male" },
  { name: "Ima Hogg", gender: "female" },
  { name: "Iona Ford", gender: "female" },
  { name: "Isabelle Ringing", gender: "female" },
  { name: "Jack Pott", gender: "male" },
  { name: "Jerry Atric", gender: "male" },
  { name: "Jim Shorts", gender: "male" },
  { name: "Joe King", gender: "male" },
  { name: "Joy Ryder", gender: "female" },
  { name: "Juan Direction", gender: "male" },
  { name: "June Bugg", gender: "female" },
  { name: "Justin Time", gender: "male" },
  { name: "Kay Oss", gender: "female" },
  { name: "Ken Tucky", gender: "male" },
  { name: "Kerry Oki", gender: "female" },
  { name: "Laura Norder", gender: "female" },
  { name: "Lee King", gender: "male" },
  { name: "Les Payne", gender: "male" },
  { name: "Lisa Carr", gender: "female" },
  { name: "Lois Price", gender: "female" },
  { name: "Lou Natic", gender: "male" },
  { name: "Lou Pole", gender: "male" },
  { name: "Luke Warm", gender: "male" },
  { name: "Marsha Mellow", gender: "female" },
  { name: "Marty Graw", gender: "male" },
  { name: "Mary Christmas", gender: "female" },
  { name: "Max Power", gender: "male" },
  { name: "Mel Function", gender: "male" },
  { name: "Mona Lott", gender: "female" },
  { name: "Neil Down", gender: "male" },
  { name: "Nick O'Time", gender: "male" },
  { name: "Noah Lott", gender: "male" },
  { name: "Norma Leigh Absent", gender: "female" },
  { name: "Olive Yew", gender: "female" },
  { name: "Otto Correct", gender: "male" },
  { name: "Paddy O'Furniture", gender: "male" },
  { name: "Paige Turner", gender: "female" },
  { name: "Pearl E. Gates", gender: "female" },
  { name: "Peg Legge", gender: "female" },
  { name: "Penny Wise", gender: "female" },
  { name: "Perry Scope", gender: "male" },
  { name: "Pete Moss", gender: "male" },
  { name: "Peter Owt", gender: "male" },
  { name: "Polly Ester", gender: "female" },
  { name: "Ray Gunn", gender: "male" },
  { name: "Reada Book", gender: "female" },
  { name: "Rhoda Horse", gender: "female" },
  { name: "Rich Kidd", gender: "male" },
  { name: "Rick Shaw", gender: "male" },
  { name: "Robin Banks", gender: "male" },
  { name: "Rocky Rhoades", gender: "male" },
  { name: "Roman Around", gender: "male" },
  { name: "Rose Bush", gender: "female" },
  { name: "Russell Sprout", gender: "male" },
  { name: "Ryan Carnation", gender: "male" },
  { name: "Sal Monella", gender: "male" },
  { name: "Sam Widge", gender: "male" },
  { name: "Sarah Bellum", gender: "female" },
  { name: "Scott Free", gender: "male" },
  { name: "Shanda Lear", gender: "female" },
  { name: "Shirley U. Jest", gender: "female" },
  { name: "Sid Down", gender: "male" },
  { name: "Skip Roper", gender: "male" },
  { name: "Sonny Day", gender: "male" },
  { name: "Stanley Cupp", gender: "male" },
  { name: "Sue Flay", gender: "female" },
  { name: "Sue Yu", gender: "female" },
  { name: "Tara Dactyl", gender: "female" },
  { name: "Teddy Bair", gender: "male" },
  { name: "Terry Bull", gender: "male" },
  { name: "Tess Tickle", gender: "female" },
  { name: "Tim Burr", gender: "male" },
  { name: "Tom Morrow", gender: "male" },
  { name: "Tyrone Shoelaces", gender: "male" },
  { name: "Uri Nation", gender: "male" },
  { name: "Vinny Gret", gender: "male" },
  { name: "Walter Melon", gender: "male" },
  { name: "Wanda Rinn", gender: "female" },
  { name: "Will Power", gender: "male" },
  { name: "Yule Log", gender: "male" },
];

export function randomSillyName(exclude?: string): string {
  const pool = exclude ? SILLY_NAMES.filter((n) => n.name !== exclude) : SILLY_NAMES;
  return pool[Math.floor(Math.random() * pool.length)].name;
}

export function sillyNamesByGender(gender: Gender): string[] {
  return SILLY_NAMES.filter((n) => n.gender === gender).map((n) => n.name);
}

export function shuffledSillyNames(): SillyName[] {
  const copy = [...SILLY_NAMES];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}
